<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2016-09-28 20:13:00
 */
return [
    'app\\assets\\AllAsset' => [
        'class' => 'app\\assets\\AllAsset',
        'basePath' => '@webroot',
        'baseUrl' => '@web',
        'js' => [
            'compiled-assets/all-0d902a6ca707e5c70047cf637aabcf3a.js',
        ],
        'css' => [
            'compiled-assets/all-8e2e6d8f5f82f2a903594f597be0f902.css',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\AuditColumnAssetsBundle' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapPluginAsset',
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\ApplicationUiAssetBundle' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset',
            'yii\\web\\YiiAsset',
            'app\\assets\\AuditColumnAssetsBundle',
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\SnowAssetsBundle' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\ApplicationUiAssetBundle',
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\widgets\\ActiveFormAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\grid\\GridViewAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\validators\\ValidationAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app\\assets\\AllAsset',
        ],
    ],
];